name: dispatch test

on:
  workflow_dispatch:
    inputs:
      Go_version:
        description: 'Version'
        required: true
        default: '1.15'
        type: choice
        options:
        - '1.16'
        - '1.14'
        - '1.15'

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
    
       - name: List files
         run: ls
         
       - name: Setup Go
         uses: actions/setup-go@v3
         with:
           go-version: ${{ inputs.Go_version }}
         
       - name: Build
         run: |
          go mod init
          go build -v ./...
         
       - name: Test with the Go CLI
         run: go test
    
       - name: Run main.go
         run: go run main.go
