name: dispatch test

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - 1.16
        - 1.14
        - 1.15

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}

       - uses: actions/checkout@v3
    
       - name: List files
         run: ls
         
       - name: Setup Go
         uses: actions/setup-go@v3
         with:
           go-version: ${{ inputs.logLevel }}
         
       - name: Build
         run: go build -v ./...
         
       - name: Test with the Go CLI
         run: go test
    
       - name: Run main.go
         run: go run main.go
