name: matrix test

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        version: [1.18, 1.19]
        
    name: Build Container   
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup GO version
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.version }}

      - name: print Go version
        run: echo ${{ matrix.version }}
        
      - name: Git clone and list files
        uses: actions/checkout@v3
        
      - name: Ls
        run: ls ${{ github.workspace }}
         
      - name: Build
        run: docker build --build-arg imageversion=${{ matrix.version }} .
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
      - name: Check versions (Os,Go) Build and Push to DockerHub
        if:  ${{ matrix.version }} != 1.18 && ${{ matrix.os }} != ubuntu-20.04
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            imageversion=${{ matrix.version }}
          push: true
          tags: dockerid21656/updated_go_image:1.0.3
